library globals;

int globalInt = 0;
bool globalBoolean = true;
String globalString = "";
String globalToken = "";
String globalTokenFB = "";
String globalTokenTemporary = "";
String globalUsername = "";
String globalPassword = "";
bool globalCheckDevice = false;
bool globalCheckMcGroup = false;
String global_subscription_id = "";
String urlLink = "";
String urlLinkWebView = "";
bool globalCheckGetListServer = false;
bool globalWaitingGetListServer = false;
double globalDouble= 10.0;
int globalVersionApp= 1;
String global_account_id= "";
String global_account_name= "";
String global_device_id= "";
String global_url= "https://hologate6.com:83";